### ISSUE TITLE
SwiftWasm 5.7 release

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/swift#4903]
Snapshot for the release channel is already set up, all feedback welcome https://github.com/swiftwasm/swift/releases/tag/swift-wasm-5.7-SNAPSHOT-2022-09-15-a

### TODO:

- [x] Check core libraries and tools are compatible with the toolchain
  - [x] JavaScriptKit: https://github.com/swiftwasm/JavaScriptKit/pull/210
  - [x] carton
    - [x] https://github.com/swiftwasm/carton/pull/380
    - [x] https://github.com/swiftwasm/carton/pull/381
  - [x] Tokamak: https://github.com/TokamakUI/Tokamak/pull/517
- [x] Set `swift-compiler-version=5.7.1` in `utils/webassembly/build-presets.ini`: https://github.com/swiftwasm/swift/commit/d23ab5c4bcfa84b9ac0a420802911fc1b1cf46d7

```console
gh workflow run manual-distribution.yml -f channel=5.7 -f toolchain_name=swift-wasm-5.7.1-RELEASE -f display_name="Swift for WebAssembly 5.7.1 Release $(date +'%Y-%m-%d')" -f display_name_short="Swift for WebAssembly 5.7.1 Release"
```

### After tagging the toolchain version

- [x] Push  a new version of [switwasm-docker](https://github.com/swiftwasm/swiftwasm-docker)
- [x] Push  a new version of [swiftwasm-action](https://github.com/swiftwasm/swiftwasm-action)
- [ ] Announcement blog post

### Current blockers

Please report any other issues found in the latest release snapshots to help us prioritize them.

**Comment by kateinoigakukun** [comment]
## 5.7.3 release

- [x] Check core libraries and tools are compatible with the toolchain
  - [x] JavaScriptKit
  - [x] carton
  - [x] Tokamak: https://github.com/TokamakUI/Tokamak/pull/532
- [x] Set `swift-compiler-version=5.7.3` in `utils/webassembly/build-presets.ini`: https://github.com/swiftwasm/swift/commit/e21efe2ce0e08f51ad9491fb0fbef82d541a5381
- [ ] Wait until https://github.com/swiftwasm/swift/actions/runs/4351386932 completed
- [ ] Trigger distribution workflow below

```
gh workflow run manual-distribution.yml -f channel=5.7 -f toolchain_name=swift-wasm-5.7.3-RELEASE -f display_name="Swift for WebAssembly 5.7.3 Release $(date +'%Y-%m-%d')" -f display_name_short="Swift for WebAssembly 5.7.3 Release"
```
