### ISSUE TITLE
SwiftWasm 5.8 release

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/swift#5362]
### TODO:

- [ ] Merge https://github.com/swiftwasm/swift/pull/5358
- [ ] Check core libraries and tools are compatible with the toolchain
  - [ ] JavaScriptKit: https://github.com/swiftwasm/JavaScriptKit/pull/210
  - [ ] carton
  - [ ] Tokamak
- [ ] Set `swift-compiler-version=5.8.0` in `utils/webassembly/build-presets.ini`
- [ ] 
```console
gh workflow run manual-distribution.yml -f channel=5.8 -f toolchain_name=swift-wasm-5.8.0-RELEASE -f display_name="Swift for WebAssembly 5.8.0 Release $(date +'%Y-%m-%d')" -f display_name_short="Swift for WebAssembly 5.8.0 Release"
```

### After tagging the toolchain version

- [ ] Push  a new version of [switwasm-docker](https://github.com/swiftwasm/swiftwasm-docker)
- [ ] Push  a new version of [swiftwasm-action](https://github.com/swiftwasm/swiftwasm-action)
- [ ] Announcement blog post

### Current blockers

Please report any other issues found in the latest release snapshots to help us prioritize them.

**Comment by tierracero** [comment]
Hope this gets resolve  soon, thanks in advanced :)
