### ISSUE TITLE
Branch cut for 5.9 release

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/swift#5395]
## TODO

- [ ] Cut `swiftwasm-release/5.9` branch from XXX, where is the most recent upstream-merge before `release/5.9` branch cut. And merge `release/5.9` changes into the branch. e95edff1a37ac46e39e49869ba88b4489c85d19e
  - `git branch swiftwasm-release/5.9 XXX`
  - `git checkout swiftwasm-release/5.9`
  - `git fetch apple release/5.9`
  - `git merge apple/release/5.9`
- [ ] Update `update-checkout-config.json`
- [ ] Update `TOOLCHAIN_CHANNEL` with `5.9` in [`.github/workflows/build-toolchain.yml`](https://github.com/swiftwasm/swift/blob/068036b9e4aeae4260ee0f4a1bd5ae79b4612d17/.github/workflows/build-toolchain.yml#L80)
- [ ] Cut corelibs release branches
  - [ ] https://github.com/swiftwasm/swift-corelibs-foundation
  - [ ] https://github.com/swiftwasm/swift-corelibs-xctest
- [ ] Fix CI docker image revision by `docker pull ghcr.io/swiftwasm/swift-ci:main-ubuntu-18.04@sha256: e5f653f13176c6c3aee5b3b864001f6ccba06584881ea0343b3822b98b084a06` style

## References
- Previous branch cut: https://github.com/swiftwasm/swift/issues/5122

**Comment by ephemer** [comment]
Just wondering if https://github.com/apple/swift-foundation might get a look for the 5.9 release (see [here](https://www.swift.org/blog/future-of-foundation/) for more info).

The fact that it splits out the ICU dependencies into a separate module could mean use cases like JSONDecoder/Encoder, NSAttributedString, etc. could be made available to devs without sacrificing binary size. That could address issues like #4171.

It should be possible to build swift-foundation manually with the 5.9 branch, but that might lead to conflicts if swift-corelibs-foundation is bundled with the toolchain. I'm not sure.

**Comment by kateinoigakukun** [comment]
The brand-new foundation is still not completely compatible with the existing corelibs-foundation, so I don't have any plan to bundle it in the toolchain for now.

**Comment by kateinoigakukun** [comment]
Added 5.9 release scheme in https://github.com/swiftwasm/swiftwasm-build/tree/main/schemes/release-5.9 and nightly toolchain is now shipped every night
