### ISSUE TITLE
SwiftWasm 5.10 release

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/swift#5570]
### TODO:

Testing with https://github.com/swiftwasm/swift/releases/tag/swift-wasm-5.10-SNAPSHOT-2024-05-30-a

- [x] Check core libraries and tools are compatible with the toolchain
  - [x] JavaScriptKit https://github.com/swiftwasm/JavaScriptKit/pull/249
  - [x] carton https://github.com/swiftwasm/carton/pull/476
- [x] Dispatch distribution workflow

```console
gh workflow run manual-distribution.yml -f run-id=$RC_RUN_ID -f scheme=release-5.10 -f override-name=swift-wasm-5.10.1-RELEASE -f display-name="Swift for WebAssembly 5.10.1 Release $(date +'%Y-%m-%d')" -f display-name-short="Swift for WebAssembly 5.10.1 Release" -R swiftwasm/swift
```
(Replace `$RC_RUN_ID` with the GitHub Actions run id for the release candidate build from [swiftwasm-build](https://github.com/swiftwasm/swiftwasm-build/actions))

### After tagging the toolchain version

- [x] Release a new version of JavaScriptKit https://github.com/swiftwasm/JavaScriptKit/releases/tag/0.19.3
- [x] Release a new version of carton
- [x] Push  a new version of [switwasm-docker](https://github.com/swiftwasm/swiftwasm-docker)
- [x] Update the setup guide in https://github.com/swiftwasm/swiftwasm-book/blob/main/src/getting-started/setup.md
- [x] Announcement blog post https://blog.swiftwasm.org/posts/5-10-released/

### Current blockers

- [x] https://github.com/apple/swift-package-manager/pull/7351
- [x] https://github.com/apple/swift-package-manager/pull/7321
- [x] A new snapshot release on release-5.10 in https://swift.org/download

Please report any other issues found in the latest release snapshots to help us prioritize them.

### Previous releases
- https://github.com/swiftwasm/swift/issues/5362
- https://github.com/swiftwasm/swift/issues/5554

**Comment by kateinoigakukun** [comment]
Update: I'm waiting for the 5.10 snapshot release from the upstream including [a fix](https://github.com/apple/swift-package-manager/pull/7351) for a while but the infrastructure is not working now. Releasing our downstream release without upstream snapshot requires a lot of build infrastructure changes. I don't have enough availability to do it now, so if you don't have any reason to stick with 5.10, please consider using 6.0 or development snapshot for now.

**Comment by kateinoigakukun** [comment]
Ok, [swift-wasm-5.10-SNAPSHOT-2024-05-30-a](https://github.com/swiftwasm/swift/releases/tag/swift-wasm-5.10-SNAPSHOT-2024-05-30-a) seems stable

**Comment by kateinoigakukun** [comment]
Trigged release workflow

```console
gh workflow run manual-distribution.yml -f run-id=9303473023 -f scheme=release-5.10 -f override-name=swift-wasm-5.10.0-RELEASE -f display-name="Swift for WebAssembly 5.10.0 Release $(date +'%Y-%m-%d')" -f display-name-short="Swift for WebAssembly 5.10.0 Release" -R swiftwasm/swift
```

**Comment by kateinoigakukun** [comment]
Published https://blog.swiftwasm.org/posts/5-10-released/
