### ISSUE TITLE
SwiftWasm 6.0 release

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/swift#5582]
### TODO:

- [x] Check core libraries and tools are compatible with the toolchain
  - [x] JavaScriptKit https://github.com/swiftwasm/JavaScriptKit/pull/268
  - [x] carton https://github.com/swiftwasm/carton/pull/498
- [x] Dispatch distribution workflow

```console
gh workflow run manual-distribution.yml -f run-id=$RC_RUN_ID -f scheme=release-6.0 -f override-name=swift-wasm-6.0-RELEASE -f display-name="Swift for WebAssembly 6.0 Release $(date +'%Y-%m-%d')" -f display-name-short="Swift for WebAssembly 6.0 Release" -R swiftwasm/swift
```
(Replace `$RC_RUN_ID` with the GitHub Actions run id of `swiftwasm-build` repository for the release candidate build)

### After tagging the toolchain version

- [ ] Release a new version of JavaScriptKit
- [ ] Release a new version of carton
- [ ] Push  a new version of [switwasm-docker](https://github.com/swiftwasm/swiftwasm-docker)
- [ ] Update the setup guide in https://github.com/swiftwasm/swiftwasm-book/blob/main/src/getting-started/setup.md
  - [ ] Add caution about `--static-swift-stdlib`
- [ ] Announcement blog post

### Current blockers

Please report any other issues found in the latest release snapshots to help us prioritize them.

### Previous releases
- https://github.com/swiftwasm/swift/issues/5362
- https://github.com/swiftwasm/swift/issues/5554
- https://github.com/swiftwasm/swift/issues/5570

**Comment by kateinoigakukun** [comment]
I'll make a stable release once the upstream tagged 6.0.2 because 6.0.1 happened during the huge diverge for swift-foundation.

**Comment by kateinoigakukun** [comment]
Rebased 6.0 channel on the upstream 6.0.2: https://github.com/swiftwasm/swiftwasm-build/pull/447

I'll execute the release workflow this week

Release candidate run id: 11568835763

**Comment by kateinoigakukun** [comment]
Executed the release workflow
```
gh workflow run manual-distribution.yml -f run-id=11568835763 -f scheme=release-6.0 -f override-name=swift-wasm-6.0.2-RELEASE -f display-name="Swift for WebAssembly 6.0.2 Release $(date +'%Y-%m-%d')" -f display-name-short="Swift for WebAssembly 6.0.2 Release" -R swiftwasm/swift
```

**Comment by kateinoigakukun** [comment]
Executed the release workflow for 6.0.3

```
gh workflow run manual-distribution.yml -f run-id=13274893214 -f scheme=release-6.0 -f override-name=swift-wasm-6.0.3-RELEASE -f display-name="Swift for WebAssembly 6.0.3 Release $(date +'%Y-%m-%d')" -f display-name-short="Swift for WebAssembly 6.0.3 Release" -R swiftwasm/swift
```
